### ISSUE TITLE
What's the confusing $6 here, there seams to be only 5 parts to the rule

### ISSUE THREAD

**Issue by JamesWP** [bisqwit/compiler_series#1]
https://github.com/bisqwit/compiler_series/blob/c9b757dad2a7d0315f875e2d47da204889df44f3/ep1/conj.y#L157

what am I missing here?

**Comment by JamesWP** [comment]
```
functions identifier1 { ctx.defun($2); ++ctx; } paramdecls colon1 stmt1
```
does `{ ctx.defun($2); ++ctx; }` count as a part?

**Comment by bisqwit** [comment]
Yes, the semantic action counts as a part.
