### ISSUE TITLE
Stop the false claims

### ISSUE THREAD

**Issue by ghost** [bisqwit/compiler_series#6]
This is a response to some false claims made which use the respected word "Engineering" in it.
Hey

@bisqwit  just wanted to say that Engineering has nothing to do with sitting behind a keyboard and writing code. There is no such thing as "reverse" "engineering". Engineering is a real subject. Engineering means designing and building real mechanical systems, like vehicular engines and turbojets. Software devs are claiming the most ridiculous of false claims these days.

Software dev is easy and for kids, and has absolutely nothing to do with a real and serious complex subject like engineering.Death to open source mindset. Open source also makes no sense and is a very salty and backwards mindset. Death to "universities" [dumpsterversities]. Death to all people who promote those evil and dumpster places.
Mechanical Engineering is the only Engineering.

bye bye

**Comment by bisqwit** [comment]
Ideology spam.
