### ISSUE TITLE
Mechanical Engineering is the only Engineering.

### ISSUE THREAD

**Issue by ghost** [bisqwit/compiler_series#7]
This is a response to some false claims made which use the respected word "Engineering" in it.

Hey
@bisqwit  just wanted to say that Engineering has nothing to do with sitting behind a keyboard and writing code. There is no such thing as "reverse" "engineering". Engineering is a real subject. Engineering means designing and building real mechanical systems, like vehicular engines and turbojets. Software devs are claiming the most ridiculous of false claims these days. Software dev is easy and for kids, and has absolutely nothing to do with a real and serious complex subject like engineering.
Mechanical Engineering is the only Engineering.
bye bye

**Comment by bisqwit** [comment]
Ideology spam.

**Comment by Demonstrandum** [comment]
English is not as plain as you think.

The word "engineering" has more than one meaning.  To engineer something is to:

(1) design and build (a machine or structure).
   * including to modify (an organism) by manipulating its genetic material. (generic engineering)

(2) skilfully arrange for (something) to occur.
